#!/usr/bin/env python3

########################################################################################################################################################################

import sys, os, shutil, argparse, platform, multiprocessing             
from   src.Python.Util.BridgeHelp import BridgeHelp
bridgeHelp = BridgeHelp()
HELP_FORMAT="%-50s %80s"
SUB_HELP_FORMAT="%-80s %10s"
class MyParser(argparse.ArgumentParser):
    def error(self, detail=None): #values=None,choice=None): #,settings = None):
        if bridgeHelp.evaluate_error(detail, sys.argv): sys.stderr.write(detail+'\n')  
        self.print_help() 
        sys.exit(2) 

    def dir_path(self,path):
        if not os.path.isdir(path): os.makedirs(path) 
        #if not os.path.isdir(path+'/logs'): os.makedirs(path+'/logs') 
        #if not os.path.isdir(path+'/tmp'): os.makedirs(path+'/tmp') 
        return path 


    def find_platform(self, p = 'NA'):
        if p == 'NA': 
            P1,P2 = platform.system().upper(), platform.platform().upper() 
            if P1[0:3] in ['MAC','DAR'] or P2[0:3] in ['MAC','DAR']: return 'mac' 
            if P1[0:3] in ['LIN','SER'] or P2[0:3] in ['LIN','SER']: return 'linux' 
            return p 
        else: 
            P = p.upper() 
            if P[0:3] in ['MAC','DAR']: return 'mac' 
            if P[0:3] in ['LIN','UNI','SER']: return 'linux' 
            return p  
        
    def force_caps(self,x): 
        return x.upper()

    def help_str(self,module):
        if module == 'prs-single':    return (HELP_FORMAT % ('Single Population PRS (Ridge Regression)',    './bridgePRS prs-single  run -o out --pop africa --pop_config afro_pop.config')) 
        if module == 'build':         return (HELP_FORMAT % ('Build large pop model to allow (port/bridge)','./bridgePRS build-model run -o out --pop euro   --pop_config euro_pop.config'))
        if module == 'prs-port':      return (HELP_FORMAT % ('Port PRS snp-weights from large to small pop','./bridgePRS prs-port    run -o out --pop afr    --model_file euro.model')) 
        if module == 'prs-prior':     return (HELP_FORMAT % ('Bridge snp-priors from large to small pop',   './bridgePRS prs-prior   run -o out --pop afr    --model_file euro.model'))
        if module == 'analyze':       return (HELP_FORMAT % ('Analyze One or More Results','./bridgePRS analyze result -o out --results out/afr.result')) 
        if module == 'easyrun':       return (HELP_FORMAT  % ('Run Following Five Modules Consecutively:','./bridgePRS easyrun go -o out --pop_config afro_pop.config eur_pop.config')) 
        if module == 'check':       return (HELP_FORMAT  % ('Check system requirements or input data','./bridgePRS check data --pop_config afro_pop.config')) 

    def sub_help_str(self, cmd, module=None):
        SUB_HELP_FORMAT="%-80s %10s"
        HS = ('INFO','INFO') 
        if cmd == 'run': HS =   ('Run The Following Module Commands:','') 
        elif cmd == 'go': HS = ('Run BridgePRS Sequentially: prs-single, build-model,prs-port,prs-prior,analyze','') 
        elif cmd == 'clump': HS = ('Load Sumstats Data, Produce SNP Clumps','') 
        elif cmd == 'beta': HS =  ('Evaluate SNP Clumps, Produce SNP Weights','') 
        elif cmd == 'predict': HS =  ('Apply SNP Weights, Produce Polygenic Predictions','') 
        elif cmd == 'quantify': HS =  ('Test Predictions, Produce Quantifiable Results','') 
        elif cmd == 'optimize': HS = ('Optimize SNP Weights,Produce Generalizable Predictions','') 
        elif cmd == 'prior': HS = ('Test Predictions,Produce SNP Prior Proability Matrix','') 
        elif cmd == 'result': HS = ('Analyze PRS Results','') 
        elif cmd == 'combine': HS = ('Combine And Analyze PRS Results','') 
        elif cmd == 'requirements': HS = ('Check System Requirements','') 
        elif cmd == 'data':         HS = ('Check Input Data','') 
        return(SUB_HELP_FORMAT % HS) 







# large 





###############################################################################################################################################


if __name__ == '__main__':
    parser=MyParser(formatter_class=argparse.RawTextHelpFormatter)
    subs = parser.add_subparsers(help=(HELP_FORMAT % ('Description','Example')),dest='module',title='Modules') 
    subs.required = True
    subs.formatter_class = argparse.RawTextHelpFormatter
    sub_help = (str(SUB_HELP_FORMAT % ('Description','')))
    
    # OPTIONS PARSERS # SUPPRESS  repeatSteps 

    Global =           MyParser(formatter_class=argparse.RawTextHelpFormatter,add_help=False)
    Global.formatter_class = argparse.RawTextHelpFormatter
    Global.add_argument('-o',             dest='outpath',      action='store',      type=str,required=True,help='Output path for bridgePRS') 
    Global.add_argument('--pop','--pops',    dest='pop',      nargs='+',      metavar='', type=parser.force_caps,default=[],required=False,help='Population Name(s)') 
    Global.add_argument('--cores',        dest='cores',        action='store',      type=int,default=0,metavar='',help='By default bridgePRS parralelized across (n-1) cores.') 
    Global.add_argument('--total_cores',       dest='total_cores',       action='store',      type=int,  metavar = '', default=multiprocessing.cpu_count(), help=argparse.SUPPRESS) 
    Global.add_argument('--verbose',      dest='verbose',      action='store_true', default=False,  help='Toggle Verbose Mode On')
    Global.add_argument('--restart',  dest='restart',  action='store_true', default=False,  help='Toggle Repeat Pipeline Steps On') 
    Global.add_argument('--noPlots',      dest='noPlots',      action='store_true', default=False,  help='Skip Post-Pipeline Plotting Analysis') 
    Global.add_argument('--silent',       dest='silent',       action='store_true', default=False,  help=argparse.SUPPRESS) 
    Global.add_argument('--pop_config','--pop_configs',   dest='pop_config',   nargs = '+',           metavar='', type=str,default=[],help='Population configuration file(s)') 
    Global.add_argument('--platform',     dest='platform',     action='store',      type=parser.find_platform,  default=parser.find_platform("NA"), help='Force platform (Linux or MacOS)') 
    Global.add_argument('--rPath',        dest='rpath',        action='store',      type=str,  default='src/Rscripts', help=argparse.SUPPRESS) 
    Global.add_argument('--plinkPath',    dest='plinkpath',    action='store',      type=str,  default='src/Python/Xtra', help=argparse.SUPPRESS) 
    Global.add_argument('--ldPath',       dest='ldpath',       nargs='+',      type=str,   metavar = '', default=[], help=argparse.SUPPRESS) 
    Global.add_argument('--ldPop',       dest='ldpop',       nargs='+',      type=str,   metavar = '', default=[], help=argparse.SUPPRESS) 
    
    
    
    Single = MyParser(add_help=False)
    Single.formatter_class = argparse.RawTextHelpFormatter
    Single.add_argument('--snp_file',    dest = 'snp_file',    nargs = '+', action = 'store', metavar='',type=str, default=[], help = 'path to snp qc file') 
    Single.add_argument('--sumstats_prefix',    dest = 'sumstats_prefix',    nargs = '+', action = 'store', metavar='',type=str, default=[], help = 'path to sumstats prefix') 
    Single.add_argument('--genotype_prefix',    dest = 'genotype_prefix',    nargs = '+', action = 'store', metavar='',type=str, default=[], help = 'path to genotype prefix') 
    Single.add_argument('--phenotype_files',    dest = 'phenotype_files',    nargs = '+', action = 'store', metavar='',type=str, default=[], help = 'phenotype test/validation data') 
    
    Single.add_argument('--sumstats_suffix',    dest = 'sumstats_suffix',    nargs = '+', action = 'store', metavar='',type=str, default=[], help = 'sumstats suffix') 
    Single.add_argument('--clump_prefix',    dest ='clump_prefix',    action = 'store', type=str, metavar='', default=None, help = 'prefix for files generated by clump step') 
    Single.add_argument('--beta_prefix',     dest ='beta_prefix',     action = 'store', type=str, metavar='', default=None, help = 'prefix for files generated by beta step') 
    Single.add_argument('--predict_prefix',  dest ='predict_prefix',  action = 'store', type=str, metavar='', default=None, help = 'prefix for files generated by predict step') 
    Single.add_argument('--phenotype',        dest='phenotype',                action='store',type=str,metavar='',   default=None,          help='Phenotype File Field: name') 
    Single.add_argument('--covariates',  dest='covariates',   action='store',type=str,metavar='',   default=None,          help='Phenotype File Field: covariates') 
    Single.add_argument('--max_clump_size',  dest='max_clump_size',   action='store',type=int , default =  '0', metavar='',  help='Max Size for Clumping') 
    #Single.add_argument('--min_maf',  dest='min_maf',   action='store',type=float , default = 0.001, metavar='',  help='Clump minumum MAF') 
    Single.add_argument('--thinned_snp_file', dest='thinned_snp_file', action='store', type = str, default = None, metavar = '', help = 'Thinned snp list for large clumps') 



    Labels = MyParser(add_help=False)
    Labels.formatter_class = argparse.RawTextHelpFormatter
    Labels.add_argument('--ssf-p',           dest='ssf-p'     ,action='store',type=str,metavar='',   default='P',          help='Sumstats field: P-value') 
    Labels.add_argument('--ssf-snpid',       dest='ssf-snpid', action='store',type=str,metavar='',   default='ID',          help='Sumstats field: snpID') 
    Labels.add_argument('--ssf-se',          dest='ssf-se',    action='store',type=str,metavar='',   default='SE',          help='Sumstats field: standard error') 
    Labels.add_argument('--ssf-ss',          dest='ssf-ss',    action='store',type=str,metavar='',   default='OBS_CT',          help='Sumstats Field: Sample Size') 
    Labels.add_argument('--ssf-beta',        dest='ssf-beta',  action='store',type=str,metavar='',   default='BETA',          help='Sumstats Field: beta') 
    Labels.add_argument('--ssf-ref',         dest='ssf-ref',   action='store',type=str,metavar='',   default='REF',          help='Sumstats Field: reference allele') 
    Labels.add_argument('--ssf-alt',         dest='ssf-alt',   action='store',type=str,metavar='',   default='A1',          help='Sumstats Field: alt allele') 
    Labels.add_argument('--ssf-maf',         dest='ssf-maf',   action='store',type=str,metavar='',   default='A1_FREQ',          help='Sumstats Field: MAF') 


    
    Build = MyParser(add_help=False)
    Build.formatter_class = argparse.RawTextHelpFormatter
    Build.add_argument('--optimize_prefix', dest = 'optimize_prefix', action = 'store', type=str, default=None, metavar='',help = 'prefix for files generated by optimize step') 
    
    
    Bridge = MyParser(add_help=False)
    Bridge.formatter_class = argparse.RawTextHelpFormatter
    Bridge.add_argument('--model_file', dest = 'model_file', action = 'store', type=str, default=None, metavar='',help = 'large population model file') 
    Bridge.add_argument('--fst', dest='fst',action='store',type=str,metavar='',default=0.15,help='fst value') 
    
    Easyrun = MyParser(add_help=False, formatter_class = argparse.RawTextHelpFormatter)
    Easyrun.add_argument('--result_files',  nargs='+',   dest='result_files',      type=str, default=[],   help='One or More PRS Result Files')  
    
    
    check             = subs.add_parser('check', help=parser.help_str('check')).add_subparsers(help=(sub_help),dest='cmd',title="Commands")
    check.required    = True
    requirements                  = check.add_parser('requirements',      parents=[Global,Single,Labels, Build,Bridge,Easyrun], help=parser.sub_help_str('requirements'))
    pop                           = check.add_parser('data',              parents=[Global,Single,Labels, Build,Bridge,Easyrun], help=parser.sub_help_str('data'))
    

    
    
    
    
    easyrun             = subs.add_parser('easyrun', help=parser.help_str('easyrun')).add_subparsers(help=(sub_help),dest='cmd',title="Commands")
    easyrun.required    = True
    go                  = easyrun.add_parser('go',      parents=[Global,Single,Labels,Build,Bridge,Easyrun], help=parser.sub_help_str('go'))
    
    

        
    # Option 1 - Single Pop, Ridge Regression # 
    prs             = subs.add_parser('prs-single', help=parser.help_str('prs-single')).add_subparsers(help=sub_help,dest='cmd',title="Commands")
    prs.required    = True
    prs.formatter_class = argparse.RawTextHelpFormatter
    run             = prs.add_parser('run',      parents=[Global,Single, Labels], help=parser.sub_help_str('run'))
    clump           = prs.add_parser('clump',    parents=[Global,Single, Labels],     help=parser.sub_help_str('clump'))
    betauate        = prs.add_parser('beta',     parents=[Global,Single, Labels],     help=parser.sub_help_str('beta'))
    predict         = prs.add_parser('predict',  parents=[Global,Single, Labels], help=parser.sub_help_str('predict'))
    quantify        = prs.add_parser('quantify', parents=[Global,Single, Labels], help=parser.sub_help_str('quantify'))
    
    
    # Option 1b - Build Euro Model #  
    build             = subs.add_parser('build-model', help=parser.help_str('build')).add_subparsers(help=(sub_help),dest='cmd',title="Commands")
    build.required    = True
    build.formatter_class = argparse.RawTextHelpFormatter
    run               = build.add_parser('run',         parents=[Global,Single, Labels,Build], help=parser.sub_help_str('run'))
    clump             = build.add_parser('clump',       parents=[Global,Single, Labels],        help=parser.sub_help_str('clump'))
    beta          = build.add_parser('beta',        parents=[Global,Single, Labels],        help=parser.sub_help_str('beta'))
    optimize          = build.add_parser('optimize',    parents=[Global,Single, Labels,Build], help=parser.sub_help_str('optimize'))
    prior             = build.add_parser('prior',       parents=[Global,Single, Labels,Build], help=parser.sub_help_str('prior'))
    

    # Option 2 - Multi-pop, PRS Portability # 
    prs_port        = subs.add_parser('prs-port', help=parser.help_str('prs-port')).add_subparsers(help=(sub_help),dest='cmd',title="Commands")
    prs_port.required    = True
    prs.formatter_class = argparse.RawTextHelpFormatter
    run             = prs_port.add_parser('run',      parents=[Global,Single,Labels,Bridge], help=parser.sub_help_str('run'))
    predict         = prs_port.add_parser('predict',  parents=[Global,Single,Labels,Bridge], help=parser.sub_help_str('predict'))
    quantify        = prs_port.add_parser('quantify', parents=[Global,Single,Labels,Bridge], help=parser.sub_help_str('quantify'))

    # Option 3 - Multi-pop, Bridge Regression  # 
    prs_bridge        = subs.add_parser('prs-prior', help=parser.help_str('prs-prior')).add_subparsers(help=(sub_help),dest='cmd',title="Commands")
    prs_bridge.required    = True
    run             = prs_bridge.add_parser('run',      parents=[Global,Single,Labels,Bridge], help=parser.sub_help_str('run'))
    clump           = prs_bridge.add_parser('clump',    parents=[Global,Single,Labels,Bridge],     help=parser.sub_help_str('clump'))
    beta        = prs_bridge.add_parser('beta',     parents=[Global,Single,Labels,Bridge],     help=parser.sub_help_str('beta'))
    predict         = prs_bridge.add_parser('predict',  parents=[Global,Single,Labels,Bridge], help=parser.sub_help_str('predict','prs-prior'))
    quantify        = prs_bridge.add_parser('quantify', parents=[Global,Single,Labels,Bridge], help=parser.sub_help_str('quantify','prs-prior'))

    # Option 4 - Analysis # 
    Analyze = MyParser(add_help=False, formatter_class = argparse.RawTextHelpFormatter)
    Analyze.add_argument('--result_files',  nargs='+',dest='result_files',type=str,required=True,help='One or More PRS Result Files')  
     
    analyze            = subs.add_parser('analyze', help=parser.help_str('analyze')).add_subparsers(help=(sub_help),dest='cmd',title="Commands")
    analyze.required   = True
    result             = analyze.add_parser('result',       parents=[Global,Analyze, Labels],     help=parser.sub_help_str('result'))
    combine            = analyze.add_parser('combine',     parents=[Global,Analyze, Labels],     help=parser.sub_help_str('combine'))






########################################################################################################################################################################

########################################################################################################################################################################
########################################################################################################################################################################
    
    args = parser.parse_args()
    
    if args.cores <= 1: args.cores = 1 
    elif args.cores > args.total_cores: args.cores = args.total_cores  
    if args.platform not in ['mac','linux']:  parser.error('Unrecognized platform '+args.platform+' (--platform linux/mac are supported)') 
    
     
    
    cwd, mydir = os.getcwd(), "/".join(os.path.abspath(sys.argv[0]).split('/')[0:-1])
    if not os.path.isdir(args.outpath): os.makedirs(args.outpath)                                                                                                                                                                                                                                   
    if args.restart: 
        for f in os.listdir(args.outpath):
            if not os.path.isdir(args.outpath+'/'+f): os.remove(args.outpath+'/'+f)  
            elif f != 'save':                         shutil.rmtree(args.outpath+'/'+f)  
    for d in ['/logs','/tmp','/save']: 
        if not os.path.isdir(args.outpath+d): os.makedirs(args.outpath+d)                                                                                                                                                                                                                  
    from src.Python.BridgePRS import BridgePRS
    bridgePRS = BridgePRS(args,mydir,cwd,sys.argv)
    sys.exit() 

